apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  annotations:
    cloudstack.apache.org/load-balancer-serviceoffering: "your-lb-offering"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 880
      targetPort: 80

